<?php
/**
 * Implements hoo_help()
 *
 * Display help and module information.
 * */

function fun_help($path, $arg){
    switch ($path) {
        case "admin/help#fun":
            return '<p>'.t('This should display').'</p>';
            break;
    }
}

/**
 * Implements hook_block_info()
*/

function fun_block_info() {
    $blocks = array();

    $blocks['list_modules'] = array(
        'info' => t('list modules'),
        'cache' => DRUPAL_NO_CACHE,
    );

    return $blocks;
}

/**
 * Implements hook_block_view()
*/

function fun_block_view($block_name) {
    if ($block_name == 'list_modules') {
        $list = module_list();
    }
}

?>